// geo-app-client/src/temp/app/auth/components/AuthCard.tsx
import { useState } from "react";

type Props = {
    title: string;
    isSignUp?: boolean,
    onSubmit: (login: string, password: string) => void,
    onFlip: () => void;
};

export default function AuthCard({ title, isSignUp, onSubmit, onFlip }: Props) {
    const [login, setLogin] = useState("");
    const [password, setPassword] = useState("");
    const [repeatPassword, setRepeatPassword] = useState("");
    const reset = () => {
        setLogin("")
        setPassword("")
        setRepeatPassword("")
    }
    const submit = (e: React.MouseEvent) => {
        e.preventDefault();
        onSubmit(login, password)
        reset();
    }
    const flip = (e: React.MouseEvent) => {
        e.preventDefault();
        onFlip();
        reset();
    }
    return <>
        <section className="card card-body flex-initial bg-base-100 shadow-xl">
            <h3 className="app-title-3 text-center mb-3">{title}</h3>
            <input type="text" className="input mb-3" placeholder="Логин" value={login} onChange={e => setLogin(e.target.value)}/>
            <input placeholder="Пароль" className="input mb-3" value={password} onChange={e => setPassword(e.target.value)} type="password" />
            {isSignUp && <input className="input mb-3" placeholder="Повторить пароль" value={repeatPassword} onChange={e => setRepeatPassword(e.target.value)} type="password" />}
            <div className="flex items-center">
                <button className="btn btn-primary" onClick={submit}>{isSignUp ? 'Зарегистрироваться' : 'Войти'}</button>
                <button className="btn btn-link"  onClick={flip}>{isSignUp ? 'Логин' : 'Регистрация'}</button>
            </div>
        </section>
    </>
}

// geo-app-client/src/views/Auth/components/AuthCard.vue
<template>
    <v-card :title="title" max-width="320">
        <v-form class="px-3 py-3">
            <v-text-field label="Логин" v-model="login" />
            <v-text-field label="Пароль" v-model="password" />
            <v-text-field label="Повторить пароль" v-model="repeatPassword" v-if="isSignUp" />
            <div className="flex items-center">
                <v-btn variant="elevated" @click="submit">{{isSignUp ? 'Зарегистрироваться' :
                    'Войти'}}</v-btn>
                <v-btn variant="text" @click="emit('flip')">{{ isSignUp ? 'Логин' : 'Регистрация' }}</v-btn>
            </div>
        </v-form>
    </v-card>
</template>

<script setup lang="ts">
import { ref } from 'vue'
const props = defineProps<{
    title: string;
    isSignUp?: boolean
}>()
const emit = defineEmits<{ flip: []; submit: [payload: { login: string; password: string }] }>()

const login = ref('')
const password = ref('')
const repeatPassword = ref('')

function submit() {
    emit('submit', {
        login: login.value,
        password: password.value
    })
}
</script>
